# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simple_raft.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11simple_raft.proto\x12\x0bsimple_raft\"\"\n\x10HeartbeatRequest\x12\x0e\n\x06nodeId\x18\x01 \x01(\t\"$\n\x11HeartbeatResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"!\n\x0e\x43ommandRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"2\n\x0f\x43ommandResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06result\x18\x02 \x01(\t2\xa2\x01\n\x04Raft\x12L\n\tHeartbeat\x12\x1d.simple_raft.HeartbeatRequest\x1a\x1e.simple_raft.HeartbeatResponse\"\x00\x12L\n\rSubmitCommand\x12\x1b.simple_raft.CommandRequest\x1a\x1c.simple_raft.CommandResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'simple_raft_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HEARTBEATREQUEST']._serialized_start=34
  _globals['_HEARTBEATREQUEST']._serialized_end=68
  _globals['_HEARTBEATRESPONSE']._serialized_start=70
  _globals['_HEARTBEATRESPONSE']._serialized_end=106
  _globals['_COMMANDREQUEST']._serialized_start=108
  _globals['_COMMANDREQUEST']._serialized_end=141
  _globals['_COMMANDRESPONSE']._serialized_start=143
  _globals['_COMMANDRESPONSE']._serialized_end=193
  _globals['_RAFT']._serialized_start=196
  _globals['_RAFT']._serialized_end=358
# @@protoc_insertion_point(module_scope)
